#!/bin/sh
set -e
export LC_ALL=C

# emconfigure scripts/fribidi-config
# emmake scripts/fribidi-build "$@"
# emmake scripts/bzip2-build "$@"
# emconfigure scripts/zlib-config
# emmake scripts/zlib-build "$@"
# emcmake scripts/libpng-config
# emmake scripts/libpng-build "$@"
# emconfigure scripts/freetype-config
# emmake scripts/freetype-build "$@"
# emconfigure scripts/harfbuzz-config
# emmake scripts/harfbuzz-build "$@"
# emconfigure scripts/freetype-clean
# emconfigure scripts/freetype-config
# emmake scripts/freetype-build "$@"
# emconfigure scripts/libexpat-config
# emmake scripts/libexpat-build "$@"
# emconfigure scripts/fontconfig-config
# emmake scripts/fontconfig-build "$@"
# emconfigure scripts/libass-config
# emmake scripts/libass-build "$@"
# emconfigure scripts/dav1d-config
# emmake scripts/dav1d-build "$@"
# emconfigure scripts/libplacebo-config
# emmake scripts/libplacebo-build "$@"
emconfigure scripts/ffmpeg-config
emmake scripts/ffmpeg-build "$@"
emcmake scripts/sdl-config
emmake scripts/sdl-build "$@"
echo "includedir=$(realpath openal/include)
prefix=$EMSDK/upstream/emscripten/cache/sysroot" | cat - openal.pc > build_libs/lib/pkgconfig/openal.pc
emconfigure scripts/mpv-config
emmake scripts/mpv-build "$@"
