#!/bin/sh
export LC_ALL=C

scripts/fribidi-clean
scripts/bzip2-clean
scripts/zlib-clean
scripts/libpng-clean
scripts/freetype-clean
scripts/harfbuzz-clean
scripts/libexpat-clean
scripts/fontconfig-clean
scripts/libass-clean
scripts/dav1d-clean
scripts/libplacebo-clean
# scripts/openssl-clean
scripts/ffmpeg-clean
scripts/sdl-clean
scripts/libxml2-clean
scripts/libudfread-clean
scripts/libbluray-clean
scripts/mpv-clean
rm -rf build_libs
