#!/bin/bash
set -e

echo() { printf %s\\n "$*"; }  # depends on standard IFS (which we have)

BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/ffmpeg_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/ffmpeg_options) "$@"
    unset -v IFS
fi

export CFLAGS="-sUSE_PTHREADS -sMEMORY64"
LDFLAGS="$CFLAGS -sINITIAL_MEMORY=33554432" # 33554432 bytes = 32 MB
# need to link against stdc++ in case libplacebo was built with glslang,
# which requires that
export LDFLAGS="$LDFLAGS -lstdc++"

OPTIONS=(
    --target-os=none        # use none to prevent any os specific configurations
    --arch=x86_32           # use x86_32 to achieve minimal architectural optimization
    --enable-cross-compile  # enable cross compile
    --disable-x86asm        # disable x86 asm
    --disable-inline-asm    # disable inline asm
    --disable-stripping     # disable stripping
    --disable-programs      # disable programs build (incl. ffplay, ffprobe & ffmpeg)
    --disable-doc           # disable doc
    --disable-sdl2
    --enable-gpl
    --disable-debug 
    --enable-static
    --disable-shared
    --extra-cflags="$CFLAGS"
    --extra-cxxflags="$CFLAGS"
    --extra-ldflags="$LDFLAGS"
    --nm="llvm-nm"
    --ar=emar
    --ranlib=emranlib
    --cc=emcc
    --cxx=em++
    --objcc=emcc
    --dep-cc=emcc
)

if "$BUILD"/scripts/test-libmpv ; then
    OPTIONS+=("--enable-pic")
fi

# Do FFmpeg's job.
if ( echo "${OPTIONS[*]}" "$@" | \
    grep -q -E -e "-openssl|-gnutls|-mbedtls|-libtls|-schannel|-securetransport" )
then
    echo TLS/SSL user option specified, skipping autodetection
else
    if pkg-config gnutls ; then
        OPTIONS+=("--enable-gnutls")
        echo "Auto-enabling GnuTLS."
    elif pkg-config openssl ; then
        OPTIONS+=("--enable-nonfree")
        OPTIONS+=("--enable-openssl")
        echo "Auto-enabling OpenSSL (creates a non-redistributable binary)."
    fi
fi

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

echo Using ffmpeg options: "${OPTIONS[*]}" "$@"

mkdir -p "$BUILD"/ffmpeg_build
cd "$BUILD"/ffmpeg_build
"$BUILD"/ffmpeg/configure --prefix="$BUILD"/build_libs "${OPTIONS[@]}" "$@"
