#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/freetype_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/freetype_options) "$@"
    unset -v IFS
fi

export CFLAGS="-sUSE_PTHREADS"
export LDFLAGS="$CFLAGS -sWASM_BIGINT"
OPTIONS="-DCMAKE_PREFIX_PATH=$BUILD/build_libs"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/freetype
cmake -B build -S . -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs" -DCMAKE_INSTALL_LIBDIR="$BUILD/build_libs/lib" $OPTIONS "$@"

