#!/bin/sh
set -e

BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/harfbuzz_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/harfbuzz_options) "$@"
    unset -v IFS
fi

export CFLAGS="-sUSE_PTHREADS"
export CPPFLAGS=$CFLAGS
OPTIONS="-Ddefault_library=static -Dtests=disabled --wrap-mode=default -Dc_args=$CFLAGS -Dcpp_args=$CPPFLAGS"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/harfbuzz

test -d build && OPTIONS="$OPTIONS --wipe"
echo Using harfbuzz options: $OPTIONS "$@"

meson setup build --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" --cross-file "$BUILD/emscripten.ini" $OPTIONS "$@"
