#!/bin/sh
set -e

make -C libbluray install "$@"
cp libbluray/src/libbluray/hdmv/mobj_data.h libbluray/src/libbluray/bdnav/mpls_data.h libbluray/src/libbluray/bdnav/uo_mask_table.h build_libs/include/libbluray