#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"

if test -f "$BUILD/libexpat_options" ; then
    IFS=$newline
    set -- $(cat "$BUILD/libexpat_options") "$@"
    unset -v IFS
fi

export CFLAGS="-sUSE_PTHREADS"
OPTIONS="--enable-static --disable-shared"

cd "$BUILD/libexpat/expat"

./buildconf.sh
./configure --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" $OPTIONS "$@"
