#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/libpng_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/libpng_options) "$@"
    unset -v IFS
fi

export CFLAGS="-sMEMORY64 -sUSE_PTHREADS"
OPTIONS="-DZLIB_LIBRARY=$BUILD/build_libs/libs/libz.a -DZLIB_INCLUDE_DIR=$BUILD/build_libs/include -DPNG_TESTS=OFF -DPNG_TOOLS=OFF"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/libpng
cmake -B build -S . -DCMAKE_INSTALL_PREFIX="$BUILD/build_libs" -DCMAKE_INSTALL_LIBDIR="$BUILD/build_libs/lib" $OPTIONS "$@"