#!/bin/sh
set -e

BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/libplacebo_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/libplacebo_options) "$@"
    unset -v IFS
fi

export CFLAGS="-sUSE_PTHREADS"
OPTIONS="-Ddefault_library=static -Dtests=false -Ddemos=false -Dc_args=$CFLAGS -Dc_link_args=$CFLAGS -Dcpp_args=$CFLAGS -Dcpp_link_args=$CFLAGS"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/libplacebo

test -d build && OPTIONS="$OPTIONS --wipe"
echo Using libplacebo options: $OPTIONS "$@"

meson setup build --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" --cross-file "$BUILD/emscripten.ini" $OPTIONS "$@"
