#!/bin/sh
set -e
BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/libudfread_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/libudfread_options) "$@"
    unset -v IFS
fi

export CFLAGS="-sUSE_PTHREADS"
export LDFLAGS="$CFLAGS -sWASM_BIGINT"
OPTIONS="--enable-static --disable-shared"

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

cd "$BUILD"/libudfread
./bootstrap
./configure --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" $OPTIONS "$@"