#!/bin/sh
set -e

BUILD="$(pwd)"
newline="
"

if test -f "$BUILD"/mpv_options ; then
    IFS=$newline
    set -- $(cat "$BUILD"/mpv_options) "$@"
    unset -v IFS
fi

case "$PKG_CONFIG_PATH" in
  '')
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig"
    ;;
  *)
    export PKG_CONFIG_PATH="$BUILD/build_libs/lib/pkgconfig:$PKG_CONFIG_PATH"
    ;;
esac

export PKG_CONFIG="/usr/bin/pkg-config"
OPTIONS="-Ddefault_library=static -Dlibmpv=true -Dc_args=['-sUSE_PTHREADS','-sMEMORY64'] -Dopenal=enabled"

echo Using mpv options: $OPTIONS "$@"

cd "$BUILD"/mpv

# add missing private dependencies from libass.pc
# this is necessary due to the hybrid static / dynamic nature of the build
# need to link against stdc++ in case libplacebo was built with glslang,
# which requires that
export LDFLAGS="$LDFLAGS $(pkg-config --libs fontconfig harfbuzz fribidi) -sUSE_PTHREADS -sINITIAL_MEMORY=33554432 -sMEMORY64=1 -lstdc++"
meson setup build --prefix="$BUILD/build_libs" --libdir="$BUILD/build_libs/lib" --cross-file "$BUILD/emscripten.ini" $OPTIONS "$@"
